### ISSUE TITLE
Latest commit(23177d5afa6f4559309a8a5552d64b913706ceba) failing in test.

### ISSUE THREAD

**Issue by nabsha** [jdereg/n-cube#176]
Latest commit(23177d5afa6f4559309a8a5552d64b913706ceba) failing in test.

'''
Failed tests: 
  TestThreading.test:83->runTest:244 expected:<0> but was:<625>
  TestThreading.test:83->runTest:244 expected:<0> but was:<625>
Tests in error: 
  TestNCube.testReloadGroovyClass:3767 » FileNotFound /tmpAbc.groovy (Permission...

'''

**Comment by jdereg** [comment]
pull request merged.  Tests passing on my Mac Book Pro.

**Comment by jdereg** [comment]
Th
