### ISSUE TITLE
Proprietary oracle driver breaking the maven build as ojdbc8 dependency not satisfied

### ISSUE THREAD

**Issue by nabsha** [jdereg/n-cube#271]
mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building n-cube 4.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.oracle:ojdbc8:jar:12.2.0.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.954 s
[INFO] Finished at: 2017-04-16T18:16:08+10:00
[INFO] Final Memory: 20M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project n-cube: Could not resolve dependencies for project com.cedarsoftware:n-cube:jar:4.0.0-SNAPSHOT: Failure to find com.oracle:ojdbc8:jar:12.2.0.1 in xxxx was cached in the local repository, resolution will not be reattempted until the update interval of repo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jsnyder4** [comment]
Hi Nabeel,

It's not a proprietary ojdbc driver. You can find it here: http://www.oracle.com/technetwork/database/features/jdbc/jdbc-ucp-122-3110062.html

Here are instructions on how to install it locally:
https://www.mkyong.com/maven/how-to-add-oracle-jdbc-driver-in-your-maven-local-repository/

I also just found this. I haven't tried it personally, but it may be helpful for you:
http://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9010

**Comment by nabsha** [comment]
Hi Josh,

I could'nt find any usage of this library, in the project(except a commented block), any place where we are using it?

**Comment by jsnyder4** [comment]
The Oracle driver is intended to be used by application by setting the following in application.properties:
```
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver
spring.datasource.url=jdbc:hsqldb:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.tomcat.validation-query=SELECT 1 FROM n_cube WHERE 1=0```

Instead of using the defaulted HSQLDB properties, you would set up an Oracle connection there.

**Comment by nabsha** [comment]
shouldn't that driver be added to classpath separately? probably as part of the particular application build instead of here?

**Comment by jdereg** [comment]
The most recently integrated PR should address this issue.
