### ISSUE TITLE
"Hello World" Example or Equivalent?

### ISSUE THREAD

**Issue by scott-m-sarsfield** [jdereg/n-cube#375]
Hi,  I've been tasked with evaluating various rule engines and this project was included.

However, I'm having some difficulty figuring out how I would incorporate it.  Perhaps there's a specific project that uses it...?

For the sake of argument, let's say I want to use it to power a subscription service where end users define when to receive alerts.  Let's say data comes in for issues with priority and status and the engine needs to only inform (evaluate true?) when something is CRITICAL and NEW / OPEN (respectively).

...i'd think that'd be fairly basic...

Thanks.
- Scott

**Comment by jdereg** [comment]
Scott, got your message.  What you have request would be very easy to handle with n-cube.  There is so much it can do.  There is a major release being finished, and then expect a lot of documentation effort shortly there after. 

Ahead of that, I can get you a 'Getting Started' sample that will be geared toward your request.  GI will need a few days to pull that together.

**Comment by jsnyder4** [comment]
Hi Scott,

I put together a Groovy test class that demonstrates how create and use some NCubes for your subscription alerts. The class could be converted to Java if you're more familiar with that, but Groovy is included in the n-cube library. You can create NCubes a few different ways:
1. Programatically
2. From json
3. Via a GUI editor, see https://github.com/jdereg/n-cube-editor

The screenshots included are from the editor. Feel free to copy the code below into your project to start learning how NCubes work. I included a few examples:

**1. testBasicDecisionNCube()**
Create a basic decision table NCube that returns true when priority = critical and status = open.

![basic](https://user-images.githubusercontent.com/15789204/29713932-e39d237a-896e-11e7-83a1-ca0c1fe6c876.png)

**2. testDecisionNCubeWithDefaults()**
Utilize default columns to allow for expansion of what values can be sent in for decision variables. For example, your consuming system starts with only sending low and critical for priority value, but later it could potentially send low, medium, high or critical. This NCube will work in both cases.

![defaults](https://user-images.githubusercontent.com/15789204/29714123-a1bc2fae-896f-11e7-9b39-bef2347d7048.png)

**3. testDecisionLoadedFromJson()**
Same as 2, except loaded from the json at the bottom of the test class.

**4. testAlertsWithThreeDecisionVariables()**
Added user as a new decision variable so you can see how decision tables can be 2, 3 or even n dimensions.

![users](https://user-images.githubusercontent.com/15789204/29714182-fa5251de-896f-11e7-876e-5c8e521c3ace.png)

This is just a taste of what you can do with the n-cube library. Hopefully, this gets you started, but please reach out if you have any more questions or need help consuming, testing or setting it up.


```import com.cedarsoftware.ncube.Axis
import com.cedarsoftware.ncube.AxisType
import com.cedarsoftware.ncube.AxisValueType
import com.cedarsoftware.ncube.Column
import com.cedarsoftware.ncube.NCube
import org.junit.Test

class SubscriptionAlertsTest
{
    @Test
    void testBasicDecisionNCube()
    {
        // Create new NCube
        NCube alerts = new NCube('Alerts')
        // Set the default return value for all cells to false
        alerts.defaultCellValue = false

        // Each decision variable translates into an Axis (think key of a Map)
        Axis priority = new Axis('priority', AxisType.DISCRETE, AxisValueType.CISTRING, false)
        // Each potential value for the decision translates into a Column (think value of a Map)
        priority.addColumn('low')
        priority.addColumn('medium')
        priority.addColumn('high')
        priority.addColumn('critical')
        alerts.addAxis(priority)

        // Repeat for other decision variable like status
        Axis status = new Axis('status', AxisType.DISCRETE, AxisValueType.CISTRING, false)
        status.addColumn('open')
        status.addColumn('pending')
        status.addColumn('closed')
        alerts.addAxis(status)

        // Set cells where decision should evaluate to true
        alerts.setCell(true, [priority: 'critical', status: 'open'])

        checkAsserts(alerts)
    }

    @Test
    void testDecisionNCubeWithDefaults()
    {
        NCube alerts = new NCube('Alerts')
        alerts.defaultCellValue = false

        // Notice the hasDefault argument is set to true this time
        // This eliminates the need to define ALL potential priority values and only the ones that matter
        Axis priority = new Axis('priority', AxisType.DISCRETE, AxisValueType.CISTRING, true)
        priority.addColumn('critical')
        alerts.addAxis(priority)

        // Repeat for other decision variable like status, hasDefault argument also true
        Axis status = new Axis('status', AxisType.DISCRETE, AxisValueType.CISTRING, true)
        status.addColumn('open')
        alerts.addAxis(status)

        // Set cells where decision should evaluate to true
        alerts.setCell(true, [priority: 'critical', status: 'open'])

        checkAsserts(alerts)
    }

    @Test
    void testDecisionLoadedFromJson()
    {
        // NCubes can also be written in json, see below for the json of the testDecisionNCubeWithDefaults() example
        NCube alerts = NCube.fromSimpleJson(JSON)
        checkAsserts(alerts)
    }

    @Test
    void testAlertsWithThreeDecisionVariables()
    {
        // Here's an example with user added as third decision variable
        NCube alerts = new NCube('Alerts')
        alerts.defaultCellValue = false

        Axis priority = new Axis('priority', AxisType.DISCRETE, AxisValueType.CISTRING, true)
        priority.addColumn('critical')
        alerts.addAxis(priority)

        Axis status = new Axis('status', AxisType.DISCRETE, AxisValueType.CISTRING, false)
        status.addColumn('open')
        status.addColumn('pending')
        status.addColumn('closed')
        alerts.addAxis(status)

        Axis user = new Axis('user', AxisType.DISCRETE, AxisValueType.CISTRING, false)
        user.addColumn('Federer')
        user.addColumn('Nadal')
        user.addColumn('Djokovic')

        // Advanced: set default column value for Nadal to true. If user = Nadal, the cell will evaluate to true
        Column nadal = user.findColumn('Nadal')
        nadal.setMetaProperty('default_value', true)
        alerts.addAxis(user)

        // Djokovic is only notified when priority = critical and status = open
        alerts.setCell(true, [priority: 'critical', status: 'open', user: 'Djokovic'])

        // Federer is only notified when status = closed
        alerts.setCell(true, [priority: 'critical', status: 'closed', user: 'Federer'])
        alerts.setCell(true, [status: 'closed', user: 'Federer'])


        // Here are a few asserts to get you started. Feel free to add your own
        assert true == alerts.getCell([priority: 'low', status: 'open', user: 'Nadal'])
        assert true == alerts.getCell([status: 'pending', user: 'Nadal']) // You don't have to pass decision variables with hasDefault = true
        assert false == alerts.getCell([priority: 'low', status: 'open', user: 'Djokovic'])
        assert false == alerts.getCell([priority: 'high', status: 'pending', user: 'Djokovic'])
        assert false == alerts.getCell([priority: 'high', status: 'pending', user: 'Federer'])
        assert true == alerts.getCell([priority: 'high', status: 'closed', user: 'Federer'])
    }

    private static void checkAsserts(NCube ncube)
    {
        assert false == ncube.getCell([priority: 'low', status: 'open'])
        assert false == ncube.getCell([priority: 'low', status: 'pending'])
        assert false == ncube.getCell([priority: 'low', status: 'closed'])
        assert false == ncube.getCell([priority: 'medium', status: 'open'])
        assert false == ncube.getCell([priority: 'medium', status: 'pending'])
        assert false == ncube.getCell([priority: 'medium', status: 'closed'])
        assert false == ncube.getCell([priority: 'high', status: 'open'])
        assert false == ncube.getCell([priority: 'high', status: 'pending'])
        assert false == ncube.getCell([priority: 'high', status: 'closed'])
        assert true == ncube.getCell([priority: 'critical', status: 'open']) // <== this one!
        assert false == ncube.getCell([priority: 'critical', status: 'pending'])
        assert false == ncube.getCell([priority: 'critical', status: 'closed'])
    }

    private final static String JSON = """{
  "ncube":"Alerts",
  "defaultCellValueType":"boolean",
  "defaultCellValue":false,
  "axes":[
    {
      "name":"priority",
      "hasDefault":true,
      "type":"DISCRETE",
      "valueType":"CISTRING",
      "preferredOrder":1,
      "fireAll":false,
      "columns":[
        {
          "id": "critical",
          "type":"string",
          "value":"critical"
        }
      ]
    },
    {
      "name":"status",
      "hasDefault":true,
      "type":"DISCRETE",
      "valueType":"CISTRING",
      "preferredOrder":1,
      "fireAll":false,
      "columns":[
        {
          "id": "open",
          "type":"string",
          "value":"open"
        }
      ]
    }
  ],
  "cells":[
    {
      "id":[
        "critical",
        "open"
      ],
      "type":"boolean",
      "value":true
    }
  ]
}"""

}```

**Comment by scott-m-sarsfield** [comment]
Wow.

I'm impressed by the quick reply and the comprehensive example.

The JSON example in particular looks ideal for what I'm working on. (We're having end users essentially create their subscriptions, probably with a custom UI). 

I'm curious how I could use this if a customer wants to be alerted about something during a time interval. (like between 5am - 1pm)

Seeing a breakdown of the JSON format could help.

(I can create a separate "issue" if you wish.  In terms of the original question, it's been resolved.  This is just scope creep.)

**Comment by scott-m-sarsfield** [comment]
@jdereg Ah, sorry if this is a premature nudge for documentation.  So, is there a tentative date on the major release?

(Side thought: pertaining to the JSON breakdown, I recognize that nothing's stopping me from looking at the code and figuring that out myself.  I guess I'm just lazy.)

**Comment by jsnyder4** [comment]
Scott,

Check out [AxisType](https://github.com/jdereg/n-cube/blob/master/src/main/groovy/com/cedarsoftware/ncube/AxisType.groovy), especially AxisType.RANGE. You can see the basic JSON format in the code example above. Like John said, full documentation is on the list of to do items and JSON format would be a great one to add.

For now, you can create an NCube using code like the examples above. At the end, use the  `toFormattedJson()` method. That will let you use some trial and error to see what the format looks like. For example...

```
NCube ncube = new NCube('TestJson')
...
code to build your NCube
...
ncube.toFormattedJson()
```
Let us know if you have more questions. Happy to help!

Josh

**Comment by scott-m-sarsfield** [comment]
Thanks for all the help.

Unfortunately, my boss wants to use something a bit more "tried and true", like Drools.

I'll close the issue since it's been adequately addressed.  Thanks.

- Scott
