### ISSUE TITLE
Documentation and examples 

### ISSUE THREAD

**Issue by TarikChrouki** [jdereg/n-cube#453]
Hi,

I want to test n-cube to build rules engine, but I have difficulties to evaluate the different use cases.

Do you have any detailed documentation or tests to see examples of implementations?

Ps :I already saw the example in ticket #375 

Thanks, 
Tarik

**Comment by jnunderwood** [comment]
I am very interested in using this n-cube in my Grails project. However, the lack of documentation and examples is really hindering my ability to get started. Is there a simple HelloWorld example? Thank you!

**Comment by jdereg** [comment]
Please look at the Rules Engine and Decision Table user guides, linked to from the main NCube GitHub page.
